name: flutter_liveness_detection
description: "A Flutter plugin for liveness detection with randomized challenge response method"
version: 1.2.1
homepage: "https://github.com/luk3d/flutter-liveness-detection-plugin"
repository: "https://github.com/luk3d/flutter-liveness-detection-plugin"

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.7'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  google_mlkit_face_detection: ^0.13.2
  camera: 0.10.6
  equatable: ^2.0.5
  image: ^4.0.15
  path_provider: ^2.1.3
  lottie: ^3.3.1
  collection: ^1.18.0
  screen_brightness: ^2.1.2
  shared_preferences: ^2.2.2

dependency_overrides:
  camera_android_camerax: 0.6.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bagussubagja.flutter_liveness_detection
        pluginClass: FlutterLivenessDetectionPlugin
      ios:
        pluginClass: FlutterLivenessDetectionPlugin

  assets:
    - packages/flutter_liveness_detection/src/core/assets/face-id-anim.json
    - packages/flutter_liveness_detection/src/core/assets/face-detected.json